### ISSUE TITLE
cannot invoke java.lang.comparable.compareTo(Object) because parameter1 is null. Does anyone know about this?

### ISSUE THREAD

**Issue by hpza810** [ThePornDatabase/TinyMediaManager-Plugin#6]
cannot invoke java.lang.comparable.compareTo(Object) because parameter1 is null. Does anyone know about this? it went well yesterday but all fail today @DirtyRacer1337

**Comment by DirtyRacer1337** [comment]
Try on [v4.2](https://archive.tinymediamanager.org/v4.2/)

**Comment by hpza810** [comment]
> Try on [v4.2](https://archive.tinymediamanager.org/v4.2/)

It went well on 4.3.9 yesterday. You mean I need to downgrade the  version to 4.2?

**Comment by hpza810** [comment]
> Try on [v4.2](https://archive.tinymediamanager.org/v4.2/)

Sorry. Same problem.

**Comment by hpza810** [comment]
> Try on [v4.2](https://archive.tinymediamanager.org/v4.2/)

I have tried it on both Docker and macOS, and now the scraper is not working, but it was working yesterday. I also tried switching to other scrapers, such as TMDB, and they are running normally. Additionally, I have contacted Discord, and the website and api are now fine, so I think we can basically pinpoint that there is an issue with the plugin. Can you check it when you have time? @DirtyRacer1337 @htlcalbbs

**Comment by DirtyRacer1337** [comment]
Problem on API, would be fixed soon

**Comment by hpza810** [comment]
> Problem on API, would be fixed soon

Thx

**Comment by hpza810** [comment]
> Problem on API, would be fixed soon

Still not working. Is it fixed now? @DirtyRacer1337

**Comment by DirtyRacer1337** [comment]
Should be fixed now
