### ISSUE TITLE
Scene Image

### ISSUE THREAD

**Issue by smokestacker** [ThePornDatabase/TinyMediaManager-Plugin#7]
I have tried and tried to figure out how to tell the plugin to pull the landscape images for scenes instead of poster images, but have been unsuccessful. Is this possible? It always pulls the posters, and I have to manually go pull the landscape version I want. At one point a while back, I remember it always pulled landscape. Is there an option to specify which one to grab? If not, can this be a feature request?

**Comment by DirtyRacer1337** [comment]
Plugin only provide info and not download anything, ask tmm dev about it
